version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - sam build
  post_build:
    commands:
      - sam package --output-template-file outputSamTemplate.yaml --s3-bucket just-wipes-webapp-backend

artifacts:
  type: zip
  files:
    - outputSamTemplate.yaml