AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Auto Shop CRM API

Resources:
  JustWipesCognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties: 
      # AliasAttributes: 
      #   - "phone_number"
      # LambdaConfig: 
      #   LambdaConfig
      MfaConfiguration: "OFF"
      Policies: 
        PasswordPolicy: 
           MinimumLength: 6
           RequireLowercase: True
           RequireNumbers: False
           RequireSymbols: False
           RequireUppercase: False
           TemporaryPasswordValidityDays: 3
      # Schema: 
      #   - SchemaAttribute
      # SmsAuthenticationMessage: String
      # SmsConfiguration: 
      #   SmsConfiguration
      # SmsVerificationMessage: String
      UsernameAttributes: 
        - "phone_number"
      UsernameConfiguration: 
        CaseSensitive: False
      # UserPoolAddOns: 
      #   UserPoolAddOns
      UserPoolName: "Just-Wipes"
  JustWipesCognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties: 
        AccessTokenValidity: 1
        # AllowedOAuthFlows: 
        #   - String
        # AllowedOAuthFlowsUserPoolClient: Boolean
        # AllowedOAuthScopes: 
        #   - String
        # AnalyticsConfiguration: 
        #   AnalyticsConfiguration
        # CallbackURLs: 
        #   - String
        ClientName: "just-wipes-webapp"
        # DefaultRedirectURI: String
        # ExplicitAuthFlows: 
        #   - String
        GenerateSecret: False
        # IdTokenValidity: 86400
        # LogoutURLs: 
        #   - String
        PreventUserExistenceErrors: ENABLED
        # ReadAttributes: 
        #   - String
        # RefreshTokenValidity: 315360000
        # SupportedIdentityProviders: 
        #   - String
        # TokenValidityUnits: 
        #   TokenValidityUnits
        UserPoolId: !Ref JustWipesCognitoUserPool
        # WriteAttributes: 
        #   - String