AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Just Wipes Backend

Resources:
  JustWipesCognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties: 
      MfaConfiguration: "OFF"
      Policies: 
        PasswordPolicy: 
           MinimumLength: 6
           RequireLowercase: False
           RequireNumbers: True
           RequireSymbols: False
           RequireUppercase: False
           TemporaryPasswordValidityDays: 3
      UsernameAttributes: 
        - "phone_number"
      LambdaConfig: 
        PreSignUp: !GetAtt PreSignUp.Arn
        DefineAuthChallenge: !GetAtt DefineAuthChallenge.Arn
        CreateAuthChallenge: !GetAtt CreateAuthChallenge.Arn
        VerifyAuthChallengeResponse: !GetAtt VerifyAuthChallenge.Arn
      UsernameConfiguration: 
        CaseSensitive: False
      UserPoolName: "just-wipes-webapp"

  JustWipesCognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties: 
        AccessTokenValidity: 1
        ClientName: "just-wipes-webapp"
        ExplicitAuthFlows: 
          - "ALLOW_CUSTOM_AUTH"
          - "ALLOW_REFRESH_TOKEN_AUTH"
        GenerateSecret: False
        IdTokenValidity: 1
        PreventUserExistenceErrors: "ENABLED"
        RefreshTokenValidity: 1
        UserPoolId: !Ref JustWipesCognitoUserPool

  PreSignUp:
    Type: 'AWS::Serverless::Function'
    Properties:    
      Handler: function.handler
      Runtime: nodejs10.x
      CodeUri: ./lambdas/cognito/pre-sign-up
      Description: 'Lambda function for cognito pre signup trigger'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::672841565100:role/CognitoLambdaRole'
      VpcConfig:
        SecurityGroupIds:
          - sg-fb2c0281
        SubnetIds:
          - subnet-0afb59bb4aef42c2c
          - subnet-03576e05e1e4e7a10
          - subnet-0c012bb7fafb41627

  DefineAuthChallenge:
    Type: 'AWS::Serverless::Function'
    Properties:    
      Handler: function.handler
      Runtime: nodejs10.x
      CodeUri: ./lambdas/cognito/define-auth-challenge
      Description: 'Lambda function for cognito define auth challenge trigger'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::672841565100:role/CognitoLambdaRole'
      VpcConfig:
        SecurityGroupIds:
          - sg-fb2c0281
        SubnetIds:
          - subnet-0afb59bb4aef42c2c
          - subnet-03576e05e1e4e7a10
          - subnet-0c012bb7fafb41627
      
  CreateAuthChallenge:
    Type: 'AWS::Serverless::Function'
    Properties:    
      Handler: function.handler
      Runtime: nodejs10.x
      CodeUri: ./lambdas/cognito/create-auth-challenge
      Description: 'Lambda function for cognito create auth challenge trigger'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::672841565100:role/CognitoLambdaRole'
      VpcConfig:
        SecurityGroupIds:
          - sg-fb2c0281
        SubnetIds:
          - subnet-0afb59bb4aef42c2c
          - subnet-03576e05e1e4e7a10
          - subnet-0c012bb7fafb41627

  VerifyAuthChallenge:
    Type: 'AWS::Serverless::Function'
    Properties:    
      Handler: function.handler
      Runtime: nodejs10.x
      CodeUri: ./lambdas/cognito/verify-auth-challenge
      Description: 'Lambda function for cognito verify auth challenge trigger'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::672841565100:role/CognitoLambdaRole'
      VpcConfig:
        SecurityGroupIds:
          - sg-fb2c0281
        SubnetIds:
          - subnet-0afb59bb4aef42c2c
          - subnet-03576e05e1e4e7a10
          - subnet-0c012bb7fafb41627
