AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Auto Shop CRM API

Resources:
  JustWipesCognito:
    Type: AWS::Cognito::UserPool
    Properties: 
      # AliasAttributes: 
      #   - "phone_number"
      # LambdaConfig: 
      #   LambdaConfig
      MfaConfiguration: "OFF"
      Policies: 
        PasswordPolicy: 
           MinimumLength: 6
           RequireLowercase: True
           RequireNumbers: False
           RequireSymbols: False
           RequireUppercase: False
           TemporaryPasswordValidityDays: 3
      # Schema: 
      #   - SchemaAttribute
      # SmsAuthenticationMessage: String
      # SmsConfiguration: 
      #   SmsConfiguration
      # SmsVerificationMessage: String
      UsernameAttributes: 
        - "phone_number"
      UsernameConfiguration: 
        CaseSensitive: False
      # UserPoolAddOns: 
      #   UserPoolAddOns
      UserPoolName: "Just-Wipes"