AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Auto Shop CRM API

Resources:
  JustWipesCognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties: 
      MfaConfiguration: "OFF"
      Policies: 
        PasswordPolicy: 
           MinimumLength: 6
           RequireLowercase: True
           RequireNumbers: False
           RequireSymbols: False
           RequireUppercase: False
           TemporaryPasswordValidityDays: 3
      UsernameAttributes: 
        - "phone_number"
      LambdaConfig: 
         PreSignUp: !Ref PreSignUp
         DefineAuthChallenge: !Ref DefineAuthChallenge
      UsernameConfiguration: 
        CaseSensitive: False
      UserPoolName: "Just-Wipes"

  JustWipesCognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties: 
        AccessTokenValidity: 1
        ClientName: "just-wipes-webapp"
        ExplicitAuthFlows: [ "ALLOW_CUSTOM_AUTH", "ALLOW_REFRESH_TOKEN_AUTH"]
        GenerateSecret: False
        IdTokenValidity: 1
        PreventUserExistenceErrors: ENABLED
        RefreshTokenValidity: 1
        UserPoolId: !Ref JustWipesCognitoUserPool

  PreSignUp:
    Type: 'AWS::Serverless::Function'
    Properties:    
      Handler: function.handler
      Runtime: python3.7
      CodeUri: ./lambdas/cognito/pre-sign-up
      Description: 'Lambda function for cognito pre signup trigger'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::672841565100:role/LambdaRole'
      VpcConfig:
        SecurityGroupIds:
          - sg-fb2c0281
        SubnetIds:
          - subnet-efa0a595
          - subnet-d169059d
          - subnet-cb25eaa0

  DefineAuthChallenge:
    Type: 'AWS::Serverless::Function'
    Properties:    
      Handler: function.handler
      Runtime: python3.7
      CodeUri: ./lambdas/cognito/define-auth-challenge
      Description: 'Lambda function for cognito define auth challenge trigger'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::672841565100:role/LambdaRole'
      VpcConfig:
        SecurityGroupIds:
          - sg-fb2c0281
        SubnetIds:
          - subnet-efa0a595
          - subnet-d169059d
          - subnet-cb25eaa0
      
